### ISSUE TITLE
add money to test contracts

### ISSUE THREAD

**Issue by androlo** [smartcontractproduction/sol-unit#8]
Need to be careful with this since it will include Ether.

**Comment by prashantpawar** [comment]
I am trying to send Ethers with my function call(by using `con.myFunc.value(12300)(argA, argB)`) and I am unable to send ethers with it, and getting the following error:

```
Running tests for:  ClashOfTrollsTest

Starting: ClashOfTrollsTest
Deploying contract.

Running 'testDepositFunds'
'testDepositFunds' - FAILED:
Error: Exception: invalid JUMP

Test results:
!!! Some tests FAILED !!!


Results: 0 tests out 1 succeeded.
npm ERR! Test failed.  See above for more details.
```

Does #8 talk about the above feature or shall I make a bug report for this?

**Comment by prashantpawar** [comment]
Hey Androlo, 

My repo:
https://github.com/prashantpawar/ClashOfTrolls

The test file:
https://github.com/prashantpawar/ClashOfTrolls/blob/master/tests/ClashOfTrollsTest.sol

**Comment by androlo** [comment]
Thank you. I am currently travelling but will take a look on Tuesday. It should not throw. If it works in browser compiler, it should work here.

**Comment by androlo** [comment]
Ok I am looking in to it now. A regular 'send' does  not throw for me (illegal jump is what it says when Solidity throws). Gonna add the Ether functionality as well, basically by adding a lot of Ether to the test contract and make a `assertBalance(address)` assertion. Need to look at that code to find out where the error comes from.

**Comment by androlo** [comment]
Never mind. It's probably because there's no Ether in the test contracts. Just gonna add it. It'll take a couple of days.

**Comment by androlo** [comment]
Hmm, I basically had support for it already. Just had to update some things and add a few tests. It is possible to send Ether from the test-contract now. It is also possible to decide the amount that the test-contract should have through a command-line flag.

Just to be clear - it threw because there was no money in the test contract. It throws in the browser compiler as well.
